
import { MiriamHouseScene } from './rpg/scenes/miriam_house_scene.js'

class BootScene extends Phaser.Scene {
  static ANIMATIONS = ['miriam_up', 'miriam_left', 'miriam_down', 'christina_up', 'christina_left', 'christina_down',
    'gaby_down', 'james_up', 'james_left', 'james_down', 'shuriken', 'mog_down', 'mog_left', 'mog_up', 'mog_celebrate',
    'firemagic', 'curemagic', 'airblast', 'evilmagic']

  constructor ()
  {
    super({ key: 'BootScene' })
  }

  preload () {
    this.load.tilemapTiledJSON('alcatraz_tilemap', 'assets/alcatraz.json')
    this.load.tilemapTiledJSON('alcatraz2_tilemap', 'assets/alcatraz2.json')
    this.load.tilemapTiledJSON('babysitting_tilemap', 'assets/babysitting.json')
    this.load.tilemapTiledJSON('christina_house_tilemap', 'assets/christina_house.json')
    this.load.tilemapTiledJSON('christina_house2_tilemap', 'assets/christina_house2.json')
    this.load.tilemapTiledJSON('cooking_class_tilemap', 'assets/cooking_class.json')
    this.load.tilemapTiledJSON('escape_room_tilemap', 'assets/escape_room.json')
    this.load.tilemapTiledJSON('harry_potter_tilemap', 'assets/harry_potter.json')
    this.load.tilemapTiledJSON('hiking_tilemap', 'assets/hiking.json')
    this.load.tilemapTiledJSON('kyoto_tilemap', 'assets/kyoto.json')
    this.load.tilemapTiledJSON('miriam_house_tilemap', 'assets/miriam_house.json')
    this.load.tilemapTiledJSON('miriam_house2_tilemap', 'assets/miriam_house2.json')
    this.load.tilemapTiledJSON('miriam_house3_tilemap', 'assets/miriam_house3.json')
    this.load.tilemapTiledJSON('proposal_tilemap', 'assets/proposal.json')
    this.load.tilemapTiledJSON('pub_quiz_tilemap', 'assets/pub_quiz.json')
    this.load.tilemapTiledJSON('san_francisco_tilemap', 'assets/san_francisco_tiled.json')
    this.load.tilemapTiledJSON('sunnyvale_house_tilemap', 'assets/sunnyvale_house.json')
    this.load.tilemapTiledJSON('tokyo_tilemap', 'assets/tokyo.json')
    this.load.tilemapTiledJSON('mog_tilemap', 'assets/mog.json')

    this.load.image('escaperoom_layout', 'assets/escaperoom_layout.png')
    this.load.image('escaperoom_grid', 'assets/escaperoom_grid.png')
    this.load.image('escaperoom_musicsheet', 'assets/escaperoom_musicsheet.png')
    this.load.image('chrono_trigger_ruins', 'assets/chrono_trigger_ruins.png')
    this.load.image('chrono_trigger_interior', 'assets/chrono_trigger_interior.png')
    this.load.image('town_and_city_tileset', 'assets/town_and_city_tileset.png')
    this.load.image('castle_tileset', 'assets/castle_tileset.png')
    this.load.image('dr_mario_background', 'assets/dr_mario_background2.png')
    this.load.image('jiraiya', 'assets/jiraiya.png')
    this.load.image('adrianna_up', 'assets/adrianna_up.gif')
    this.load.image('homura_down', 'assets/homura_down.gif')
    this.load.image('stitch_down', 'assets/stitch_down.png')
    this.load.image('wimble_down', 'assets/wimble_down.gif')
    this.load.image('hellokitty_down', 'assets/hellokitty_down.png')
    this.load.image('harry_down', 'assets/harry_down.png')
    this.load.image('hermione_down', 'assets/hermione_down.png')
    this.load.image('ron_down', 'assets/ron_down.png')
    this.load.image('snape_left', 'assets/snape_left.png')
    this.load.image('forest_battle', 'assets/forest_battle.gif')
    this.load.image('harry_potter_battle', 'assets/harry_potter_battle.png')
    this.load.image('hermione_battle', 'assets/hermione_battle.png')
    this.load.image('ron_battle', 'assets/ron_battle.png')
    this.load.image('snape_battle', 'assets/snape_battle.png')
    this.load.image('spider_battle1', 'assets/spider_battle1.gif')
    this.load.image('spider_battle2', 'assets/spider_battle2.gif')
    this.load.image('spider_egg_battle', 'assets/spider_egg_battle.png')
    this.load.image('voldemort_battle', 'assets/voldemort_battle.png')
    this.load.image('dementor_battle', 'assets/dementor_battle.png')
    this.load.spritesheet('dr_mario_sprites', 'assets/dr_mario_sprites2.png', { frameWidth: 19, frameHeight: 19, spacing: 1 })
    this.load.spritesheet('dr_mario_yellow_virus', 'assets/dr_mario_yellow_virus.png', { frameWidth: 20, frameHeight: 20 })
    this.load.spritesheet('dr_mario_blue_virus', 'assets/dr_mario_blue_virus.png', { frameWidth: 20, frameHeight: 20 })
    this.load.spritesheet('dr_mario_red_virus', 'assets/dr_mario_red_virus.png', { frameWidth: 20, frameHeight: 20 })
    this.load.spritesheet('miriam_up', 'assets/miriam_up.png', { frameWidth: 28, frameHeight: 48 })
    this.load.spritesheet('miriam_left', 'assets/miriam_left.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('miriam_down', 'assets/miriam_down.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('christina_up', 'assets/christina_up.png', { frameWidth: 28, frameHeight: 48 })
    this.load.spritesheet('christina_left', 'assets/christina_left.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('christina_down', 'assets/christina_down.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('james_up', 'assets/james_up.png', { frameWidth: 28, frameHeight: 48 })
    this.load.spritesheet('james_left', 'assets/james_left.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('james_down', 'assets/james_down.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('mog_up', 'assets/mog_up.png', { frameWidth: 28, frameHeight: 44 })
    this.load.spritesheet('mog_left', 'assets/mog_left.png', { frameWidth: 32, frameHeight: 44 })
    this.load.spritesheet('mog_down', 'assets/mog_down.png', { frameWidth: 32, frameHeight: 44 })
    this.load.spritesheet('mog_celebrate', 'assets/mog_celebrate.png', { frameWidth: 32, frameHeight: 42 })
    this.load.spritesheet('karen_up', 'assets/karen_up.gif', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('gaby_down', 'assets/gaby_down.png', { frameWidth: 30, frameHeight: 48 })
    this.load.spritesheet('shuriken', 'assets/shuriken.png', { frameWidth: 16, frameHeight: 16 })
    this.load.spritesheet('firemagic', 'assets/firemagic.png', { frameWidth: 32, frameHeight: 64 })
    this.load.spritesheet('curemagic', 'assets/curemagic.png', { frameWidth: 30, frameHeight: 28 })
    this.load.spritesheet('airblast', 'assets/airblast.png', { frameWidth: 32, frameHeight: 20 })
    this.load.spritesheet('evilmagic', 'assets/evilmagic.png', { frameWidth: 32, frameHeight: 32 })
    this.load.image('keys', 'assets/piano_keys_layout.png')
    this.load.audio('PianoC4', ['assets/audio/Piano.mf.C4.mp3'])
    this.load.audio('PianoD4', ['assets/audio/Piano.mf.D4.mp3'])
    this.load.audio('PianoDb4', ['assets/audio/Piano.mf.Db4.mp3'])
    this.load.audio('PianoE4', ['assets/audio/Piano.mf.E4.mp3'])
    this.load.audio('PianoEb4', ['assets/audio/Piano.mf.Eb4.mp3'])
    this.load.audio('PianoF4', ['assets/audio/Piano.mf.F4.mp3'])
    this.load.audio('PianoG4', ['assets/audio/Piano.mf.G4.mp3'])
    this.load.audio('PianoGb4', ['assets/audio/Piano.mf.Gb4.mp3'])
    this.load.audio('PianoA4', ['assets/audio/Piano.mf.A4.mp3'])
    this.load.audio('PianoAb4', ['assets/audio/Piano.mf.Ab4.mp3'])
    this.load.audio('PianoB4', ['assets/audio/Piano.mf.B4.mp3'])
    this.load.audio('PianoBb4', ['assets/audio/Piano.mf.Bb4.mp3'])
    this.load.audio('PianoC5', ['assets/audio/Piano.mf.C5.mp3'])
    this.load.audio('PianoD5', ['assets/audio/Piano.mf.D5.mp3'])
    this.load.audio('PianoDb5', ['assets/audio/Piano.mf.Db5.mp3'])
    this.load.audio('PianoE5', ['assets/audio/Piano.mf.E5.mp3'])
    this.load.audio('PianoEb5', ['assets/audio/Piano.mf.Eb5.mp3'])
    this.load.audio('PianoF5', ['assets/audio/Piano.mf.F5.mp3'])
    this.load.audio('PianoG5', ['assets/audio/Piano.mf.G5.mp3'])
    this.load.audio('PianoGb5', ['assets/audio/Piano.mf.Gb5.mp3'])
    this.load.audio('PianoA5', ['assets/audio/Piano.mf.A5.mp3'])
    this.load.audio('PianoAb5', ['assets/audio/Piano.mf.Ab5.mp3'])
    this.load.audio('PianoB5', ['assets/audio/Piano.mf.B5.mp3'])
    this.load.audio('PianoBb5', ['assets/audio/Piano.mf.Bb5.mp3'])
    this.load.audio('song', ['assets/audio/song.mp3'])
  }

  create () {
    this.scene.start('MiriamHouseScene', {startingLocation: MiriamHouseScene.startingLocationEnum.START_GAME, fadeIn: true})
    //this.scene.start('RpgBattleScene')
  }
}

export { BootScene }